version: "3.8"
services:
  app:
    build:
      context: ../
      dockerfile: ./.hub/Dockerfile
    volumes:
      - ..:/usr/src/app
      - ../node_modules:/usr/src/app/node_modules/
      - /usr/src/app/tests
    command: npm run test
